In [3]:
import pandas as pd
import numpy as np

omx_hel = pd.read_csv('datasets/omx_hel.csv')
omx_hel.dtypes

Date           object
Close/Last    float64
Open          float64
High          float64
Low           float64
dtype: object

In [4]:
health = pd.read_xml('datasets/apple_health_export/vienti.xml')
health.describe()

,MetadataEntry,activeEnergyBurned,activeEnergyBurnedGoal,appleMoveTime,appleMoveTimeGoal,appleExerciseTime,appleExerciseTimeGoal,appleStandHours,appleStandHoursGoal
count,0.0,533.000000,533.0,533.0,533.0,533.0,533.0,533.0,533.0
mean,NaN,279.726265,300.0,0.0,0.0,0.0,0.0,0.0,0.0
std,NaN,182.691676,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,NaN,0.107000,300.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,NaN,184.206000,300.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,NaN,248.113000,300.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,NaN,342.757000,300.0,0.0,0.0,0.0,0.0,0.0,0.0
max,NaN,1895.350000,300.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
health

,value,HKCharacteristicTypeIdentifierDateOfBirth,HKCharacteristicTypeIdentifierBiologicalSex,HKCharacteristicTypeIdentifierBloodType,HKCharacteristicTypeIdentifierFitzpatrickSkinType,HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse,type,sourceName,sourceVersion,unit,...,dateComponents,activeEnergyBurned,activeEnergyBurnedGoal,activeEnergyBurnedUnit,appleMoveTime,appleMoveTimeGoal,appleExerciseTime,appleExerciseTimeGoal,appleStandHours,appleStandHoursGoal
0,2024-05-11 21:09:58 +0300,None,None,None,None,None,None,None,None,None,...,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
1,None,1990-04-10,HKBiologicalSexMale,HKBloodTypeNotSet,HKFitzpatrickSkinTypeNotSet,Ei mitään,None,None,None,None,...,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
2,184,None,None,None,None,None,HKQuantityTypeIdentifierHeight,Terveys,14.2,cm,...,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
3,182,None,None,None,None,None,HKQuantityTypeIdentifierHeight,iPhone,16.1.1,cm,...,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
4,85,None,None,None,None,None,HKQuantityTypeIdentifierBodyMass,Terveys,14.2,kg,...,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292789,None,None,None,None,None,None,None,None,None,None,...,2024-05-07,457.441,300.0,kcal,0.0,0.0,0.0,0.0,0.0,0.0
292790,None,None,None,None,None,None,None,None,None,None,...,2024-05-08,551.628,300.0,kcal,0.0,0.0,0.0,0.0,0.0,0.0
292791,None,None,None,None,None,None,None,None,None,None,...,2024-05-09,343.926,300.0,kcal,0.0,0.0,0.0,0.0,0.0,0.0
292792,None,None,None,None,None,None,None,None,None,None,...,2024-05-10,241.442,300.0,kcal,0.0,0.0,0.0,0.0,0.0,0.0
292793,None,None,None,None,None,None,None,None,None,None,...,2024-05-11,116.988,300.0,kcal,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
health.columns

Index(['value', 'HKCharacteristicTypeIdentifierDateOfBirth',
       'HKCharacteristicTypeIdentifierBiologicalSex',
       'HKCharacteristicTypeIdentifierBloodType',
       'HKCharacteristicTypeIdentifierFitzpatrickSkinType',
       'HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse', 'type',
       'sourceName', 'sourceVersion', 'unit', 'creationDate', 'startDate',
       'endDate', 'device', 'MetadataEntry', 'dateComponents',
       'activeEnergyBurned', 'activeEnergyBurnedGoal',
       'activeEnergyBurnedUnit', 'appleMoveTime', 'appleMoveTimeGoal',
       'appleExerciseTime', 'appleExerciseTimeGoal', 'appleStandHours',
       'appleStandHoursGoal'],
      dtype='object')